// ============================================================
// PR Builder — create branch, apply patches, push, open PR
// ============================================================

import * as path from "path";
import { createLogger } from "./utils/logger";
import { createBranch, commitAll, pushBranch, checkoutBranch } from "./git/ops";
import { readFile, writeFile, generateDiff } from "./fs/repo";
import { createPR, addComment, addLabels } from "./github/client";
import type {
  GitHubIssue,
  GitHubRepo,
  FixResult,
  TriageResult,
  PRResult,
} from "./types";
import type { SimpleGit } from "simple-git";

const log = createLogger("pr-builder");

/**
 * Create a PR with the fix:
 * 1. Create a feature branch
 * 2. Apply patches
 * 3. Commit & push
 * 4. Open PR
 * 5. Add labels & comment on the original issue
 */
export async function buildPR(
  git: SimpleGit,
  issue: GitHubIssue,
  repo: GitHubRepo,
  triage: TriageResult,
  fix: FixResult,
  workspaceDir: string,
): Promise<PRResult> {
  log.info("Building PR", { issue: issue.number });

  // 1. Create branch
  const branchName = `bugfix/issue-${issue.number}-${Date.now()}`;
  await createBranch(git, branchName);

  // 2. Apply patches
  const diffs: string[] = [];
  for (const patch of fix.patches) {
    const fullPath = path.join(workspaceDir, patch.path);

    // Read original content for diff
    let originalContent = "";
    try {
      originalContent = await readFile(fullPath);
    } catch {
      log.warn("Original file not found, treating as new file", { path: patch.path });
    }

    // Write patched content
    await writeFile(fullPath, patch.patchedContent);
    log.info("Applied patch", { path: patch.path });

    // Generate diff for PR body
    const diff = generateDiff(originalContent, patch.patchedContent, patch.path);
    diffs.push(diff);
  }

  // 3. Commit
  const commitMsg = `fix: ${fix.summary}\n\nCloses #${issue.number}\n\nRisk: ${fix.riskAssessment}`;
  await commitAll(git, commitMsg);

  // 4. Push
  await pushBranch(git, "origin", branchName);

  // 5. Create PR
  const prBody = buildPRBody(issue, triage, fix, diffs);
  const pr = await createPR(
    repo.full_name,
    `[Auto-fix] ${fix.summary}`,
    prBody,
    branchName,
    repo.default_branch,
  );

  // 6. Add labels and comment on original issue
  await addLabels(repo.full_name, issue.number, ["auto-fix", "bug"]);
  await addComment(
    repo.full_name,
    issue.number,
    `🤖 **Auto-fix PR created:** ${pr.url}\n\n${fix.summary}\n\nRisk assessment: **${fix.riskAssessment}**`,
  );

  log.info("PR built successfully", { pr: pr.number, branch: branchName });
  return { number: pr.number, url: pr.url, branchName };
}

function buildPRBody(
  issue: GitHubIssue,
  triage: TriageResult,
  fix: FixResult,
  diffs: string[],
): string {
  const sections: string[] = [];

  sections.push(`## 🤖 Auto-Generated Fix`);
  sections.push("");
  sections.push(`**Closes:** #${issue.number}`);
  sections.push(`**Severity:** ${triage.severity}`);
  sections.push(`**Risk:** ${fix.riskAssessment}`);
  sections.push("");
  sections.push(`### Summary`);
  sections.push(fix.summary);
  sections.push("");
  sections.push(`### Changes`);
  for (const patch of fix.patches) {
    sections.push(`- **${patch.path}**: ${patch.explanation}`);
  }
  sections.push("");
  sections.push(`### Test Plan`);
  sections.push(fix.testPlan);
  sections.push("");
  sections.push(`### Diff`);
  for (let i = 0; i < diffs.length; i++) {
    const truncated = diffs[i].length > 8000
      ? diffs[i].slice(0, 8000) + "\n... (truncated)"
      : diffs[i];
    sections.push(`<details><summary>${fix.patches[i]?.path || `Patch ${i + 1}`}</summary>`);
    sections.push("");
    sections.push("```diff");
    sections.push(truncated);
    sections.push("```");
    sections.push("</details>");
    sections.push("");
  }
  sections.push("---");
  sections.push("*This PR was automatically generated by Bug Auto-Fix Agent.*");

  return sections.join("\n");
}